### ISSUE TITLE
FindPattern doesn't work as intended?

### ISSUE THREAD

**Issue by seeker25** [Heep042/kvm_explorer#3]
Seems a little buggy, but I've retrofitted this to look up patterns (was looking at the wrong addresses before doh). 

You need alot of code from your other project to make this work and the links are broken.

**Comment by h33p** [comment]
This could have been an issue with the old version of m0dular, but I have just updated it. Please, check if the issue persists.

Also, I am using relative submodule links as that allows for easy migration between repo servers. However, GitHub does not read them properly thus is unable to provide hyperlinks. It is an issue from the GitHub's end.

**Comment by seeker25** [comment]
I'm a dummy, just using git clone --recursive fixes this. I'll give it a go in a bit.

**Comment by h33p** [comment]
Updating submodules is done with `git submodule update --recursive`. There is no need to re-clone.
